update jeudi 21 décembre 2017, 17:31:44 (UTC+0100)

diff --git a/scripts/appel b/scripts/appel
--- a/scripts/appel
+++ b/scripts/appel
@@ -2,12 +2,14 @@
 
 GRPE=${1}
 SALLE=${2:-$(salle)}
-
-LOGINS=$(etudiants ${GRPE} || { echo })
+etudiants ${GRPE} >/dev/null || { echo "Error: Groupe Inexistant"; exit 1; }
+LOGINS=$(etudiants ${GRPE})
 
 for etu in ${LOGINS}
 do
-    identite ${etu}
+    if ( ! est-connecte-dans ${etu} )
+    then
+        identite ${etu}
+    fi
 done
-
 exit 0
diff --git a/scripts/est-connecte-dans b/scripts/est-connecte-dans
--- a/scripts/est-connecte-dans
+++ b/scripts/est-connecte-dans
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+pareil $# 0 && { echo "Error: login obligatoire"; exit 1; }
+
 if pareil $1 "-m"
 then
     LOGIN=${2}
@@ -11,7 +13,7 @@ else
     SHOW=0
 fi
 
-for pc in $(machines | tr '\n' ' ')
+for pc in $(machines ${lasalle})
 do
     if est-connecte-sur ${LOGIN} ${pc}
     then
diff --git a/scripts/est-connecte-sur b/scripts/est-connecte-sur
--- a/scripts/est-connecte-sur
+++ b/scripts/est-connecte-sur
@@ -1,7 +1,9 @@
 #!/bin/bash
 
+pareil $# 0 && { echo "Error: login obligatoire"; exit 1; }
+
 LOGIN=${1}
-MACHINE=${2:$(hostname)}
+MACHINE=${2:-$(hostname)}
 
 echo $(ssh ${MACHINE} users) | tr ' ' '\n' | grep -q -x -w ${LOGIN}
 
